apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-k8s-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-k8s-app
  template:
    metadata:
      labels:
        app: sample-k8s-app
    spec:
      containers:
        - name: app
          image: sample-k8s-app:latest
          ports:
            - containerPort: 80
